# ***Numpy Notebook***

In [1]:
import numpy as np

**1-D array**

In [2]:
myarr = np.array([2, 6, 8, 6, 8, 2])
print(myarr)
print(myarr.shape)

[2 6 8 6 8 2]
(6,)


*Indexing*

In [3]:
print(myarr[0])
print(myarr[1])
print(myarr[2])

2
6
8


**2-D array**

In [4]:
myarr2 = np.array([[2, 6, 9], [5, 9, 6], [8, 1, 0]], dtype = "int8")
print(myarr2)

[[2 6 9]
 [5 9 6]
 [8 1 0]]


*Indexing*

In [5]:
print(myarr2[1, 2])

6


*updating 2-d array*

In [6]:
myarr2[1, 2] = 2
print(myarr2)

[[2 6 9]
 [5 9 2]
 [8 1 0]]


In [7]:
print(myarr2.shape)
# shape tells the shape of an array as first element is for row and 2nd is for column

(3, 3)


In [8]:
print(myarr2.size)
# size will give the size of an array as the total no. of elements in the array

9


In [9]:
print(myarr2.dtype)
# dtype gives type of an array

int8


In [10]:
myarr2

array([[2, 6, 9],
       [5, 9, 2],
       [8, 1, 0]], dtype=int8)

In [11]:
zeros = np.zeros((2, 6))
# zeros gives an array of zeros, we have to give row and coloum as an arguments
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [12]:
rng = np.arange(16)
# arange function in numpy is simillar to python inbuild range function. arange gives an array of range
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [13]:
lspace = np.linspace(1, 50, 11)
# linspace gives an array of equally distributed elements. It takes 3 arguments.
# 1st and 2nd argument is for a range of no. numbers in between we want elements.
# 3rd argument is for how many elements we want between in range of 1st_arg and 2nd_arg.
print(lspace)

[ 1.   5.9 10.8 15.7 20.6 25.5 30.4 35.3 40.2 45.1 50. ]
